version: '3.8'

services:
  app_vet:
    build:
      context: .
      target: app
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:mysql://ejercicio-vet:3306/clinica_veterinaria?createDatabaseIfNotExist=true&serverTimezone=UTC
      - DB_USER_NAME=root
      - DB_PASSWORD=1234
    restart: always
    depends_on:
      ejercicio-vet:
        condition: service_healthy  # Se mueve dentro de `ejercicio-vet`

  ejercicio-vet:
    image: mysql:8.0.33
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=clinica_veterinaria
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
