version: '3.8'

services:
  app_vet:
    build:
      context: /Ejercicio-Veterinaria/.
      target: app
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://vet_db:3306/clinica_veterinaria?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER_NAME: root
      DB_PASSWORD: admin
    restart: always
    depends_on:
      vet_db:
        condition: service_healthy
    networks:
      - vet-net

  vet_db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: clinica_veterinaria
      MYSQL_ROOT_HOST: '%'
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-padmin"]
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - vet-net

networks:
  vet-net:
    driver: bridge